
let state={tab:"casos",selected:null,filter:"Todos",query:""};const app=document.getElementById("app");
const categories={"Todos":c=>true,"Padres":c=>c.tags.some(t=>["Padre","4 hijos","Hijos"].includes(t)),"Grandes pérdidas":c=>c.tags.some(t=>t.includes("kg")),"Dolores":c=>c.tags.some(t=>["Rodillas","Dolor"].includes(t)),"Autoestima":c=>c.tags.some(t=>["Autoestima","Vergüenza","Camiseta","Ropa"].includes(t)),"Desconfianza online":c=>c.tags.some(t=>["Desconfianza","Online","Experiencias malas"].includes(t)),"Poco tiempo":c=>c.tags.some(t=>["Poco tiempo","Organización","3 días"].includes(t))};
function render(){app.innerHTML=`<div class="top"><div class="top-inner"><div class="logo"><div class="logo-mark">HSB</div><div>Biblioteca<br><small style="color:#aaa">Casos Reales</small></div></div><div class="nav"><button class="${state.tab==='casos'?'active':''}" onclick="go('casos')">Casos</button><button class="${state.tab==='aprendizajes'?'active':''}" onclick="go('aprendizajes')">Aprendizajes</button></div></div></div><div class="wrap">${state.selected?detail(state.selected):state.tab==="aprendizajes"?aprendizajes():home()}</div>`}
function go(tab){state.tab=tab;state.selected=null;render()}
function home(){const q=state.query.toLowerCase();const list=CASES.filter(categories[state.filter]).filter(c=>!q||c.name.toLowerCase().includes(q)||c.title.toLowerCase().includes(q)||c.tags.join(" ").toLowerCase().includes(q));return `<section class="hero"><div class="kicker">Hombres normales · Resultados reales</div><h1>Biblioteca de Casos Reales HSB</h1><p>Historias de hombres de 35 a 60 años con trabajo, hijos, poco tiempo, dolores, dudas y barriga. No son influencers. Son personas normales que decidieron dejar de improvisar.</p><div class="stats"><div class="stat"><strong>${CASES.length}</strong> casos iniciales</div><div class="stat"><strong>35-60</strong> años</div><div class="stat"><strong>HSB</strong> método realista</div></div></section><input class="search" placeholder="Buscar por nombre, problema o etiqueta..." value="${state.query}" oninput="state.query=this.value;render()"><div class="filters">${Object.keys(categories).map(cat=>`<button class="filter ${state.filter===cat?'active':''}" onclick='state.filter=${JSON.stringify(cat)};render()'>${cat}</button>`).join("")}</div><div class="grid">${list.map(card).join("")}</div>`}
function card(c){return `<article class="card" onclick='openCase(${JSON.stringify(c.name)})'><div class="kicker">${c.name}</div><h3>${c.title}</h3><p>${c.problem.slice(0,145)}...</p><div class="tags">${c.tags.map((t,i)=>`<span class="tag ${i===0?'red':''}">${t}</span>`).join("")}</div></article>`}
function openCase(name){state.selected=CASES.find(c=>c.name===name);render()}
function detail(c){return `<button class="back" onclick="state.selected=null;render()">← Volver a casos</button><div class="detail"><aside class="panel"><div class="kicker">${c.name}</div><h1>${c.title}</h1><p>${c.age}</p><div class="tags">${c.tags.map((t,i)=>`<span class="tag ${i===0?'red':''}">${t}</span>`).join("")}</div><div class="section"><h4>Qué pensaba antes</h4><p class="quote">${c.thought}</p></div><div class="section"><h4>Lección HSB</h4><p class="lesson">${c.lesson}</p></div></aside><main class="panel"><h2>La situación inicial</h2><p>${c.problem}</p><div class="section"><h4>Qué hicimos</h4><ul>${c.process.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="section"><h4>Qué consiguió</h4><ul>${c.result.map(x=>`<li>${x}</li>`).join("")}</ul></div><div class="section"><h4>Qué puedes aprender tú</h4><p>${c.lesson}</p></div></main></div>`}
function aprendizajes(){return `<section class="hero"><div class="kicker">La idea detrás de todos los cambios</div><h1>Lo que se repite en los casos HSB</h1><p>Todos tienen historias distintas, pero casi todos comparten los mismos bloqueos: poco tiempo, miedo, vergüenza, dolores, desconfianza y años de intentos fallidos.</p></section><div class="about-grid">${box("No necesitas una vida perfecta","La mayoría empezó con trabajo, familia, cansancio y responsabilidades. El cambio no empieza cuando todo está en calma. Empieza cuando decides ordenar lo que tienes.")}${box("No necesitas más información","Muchos ya sabían qué era una proteína, una caloría o una sentadilla. El problema era no aplicar con estructura.")}${box("No necesitas entrenar 6 días","Para muchos, 3 días bien hechos fueron más útiles que años de improvisar.")}${box("No es solo la barriga","Detrás de la pérdida de grasa suele haber vergüenza, autoestima, ropa, fotos, playa, hijos y salud.")}${box("El dolor no siempre significa parar","A veces significa adaptar, aprender técnica y volver a progresar con cabeza.")}${box("El físico cambia la confianza","Cuando un hombre deja de esconderse, no solo cambia su cuerpo. Cambia cómo se mueve por el mundo.")}</div>`}
function box(t,b){return `<article class="about-card"><h3>${t}</h3><p>${b}</p></article>`}
render();
